// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRI-NWg15xXywDzQAb_jsv8fMvSfpezv0',
    appId: '1:510548844181:web:a44cdb0dccb689ca5cc59c',
    messagingSenderId: '510548844181',
    projectId: 'testing-39754',
    authDomain: 'testing-39754.firebaseapp.com',
    storageBucket: 'testing-39754.appspot.com',
    measurementId: 'G-ZME75MZZBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG31gRnPr6tX-xqo6VUxmx6xuG9HtnNVw',
    appId: '1:510548844181:android:04a23c31748487f75cc59c',
    messagingSenderId: '510548844181',
    projectId: 'testing-39754',
    storageBucket: 'testing-39754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKknpKMz4fNrp89xA1yn4BvJ5psnYhMs',
    appId: '1:510548844181:ios:298b2f07bd1c048f5cc59c',
    messagingSenderId: '510548844181',
    projectId: 'testing-39754',
    storageBucket: 'testing-39754.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKknpKMz4fNrp89xA1yn4BvJ5psnYhMs',
    appId: '1:510548844181:ios:298b2f07bd1c048f5cc59c',
    messagingSenderId: '510548844181',
    projectId: 'testing-39754',
    storageBucket: 'testing-39754.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRI-NWg15xXywDzQAb_jsv8fMvSfpezv0',
    appId: '1:510548844181:web:76889cf441b7c33c5cc59c',
    messagingSenderId: '510548844181',
    projectId: 'testing-39754',
    authDomain: 'testing-39754.firebaseapp.com',
    storageBucket: 'testing-39754.appspot.com',
    measurementId: 'G-CS11ZD2L26',
  );
}
